version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py loaddata library_db_dump.json &&
            python manage.py start_bot & 
            sleep 5 &&
            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    restart: always
    build:
      context: .
    command: celery -A library_config worker -l INFO
    volumes:
      - ./:/app

    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app

  celery-beat:
    restart: always
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &
            celery -A library_config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ./:/app

    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app