version: "3"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    container_name: library-service-api
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/code
      - ./media:/vol/web/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    env_file:
      - .env
    depends_on:
      - db
